### PR TITLE
* add satelliteOf relation

### PR DESCRIPTION
**Pull request by odanoburu**
https://github.com/own-pt/own-en/pull/3

### CODE REVIEW

**Comment by arademaker** [comment]
Why in this repo the adjs.all didn't change?

What is the `.dir-locals.el` file in the `src/` directory?

**Comment by odanoburu** [comment]
> Why in this repo the adjs.all didn't change?

I didn't really apply the fix to this repo, but the configuration file needs to be updated because this repo refers to the other. although I did notice that there are no similarTo relations in this repo.

> What is the .dir-locals.el file in the src/ directory?

https://www.gnu.org/software/emacs/manual/html_node/elisp/Directory-Local-Variables.html, just to make sure that mill-mode is activated when a lexicographer file is opened in Emacs.

**Comment by arademaker** [comment]
The configuration file needs to be updated or it was updated? 

You didn't apply the fix means that someone needs to apply it or because there is no `similarTo` relation nothing needs to be done.

**Comment by odanoburu** [comment]
> The configuration file needs to be updated or it was updated?

it is to be updated by this PR.

> You didn't apply the fix means that someone needs to apply it or because there is no similarTo relation nothing needs to be done.

that's what I'm trying to understand, I don't really remember the decisions we ended up taking since there was a bit of back and forth. I remember that we decided that we would have independent but (possibly) interliked wordnets; is that right? in this case all the relations that are in own-en should also be in own-pt, and then the lack of the similarTo relations is a bug. if that's the case I'll open an issue.

**Comment by arademaker** [comment]
> I remember that we decided that we would have independent but (possibly) interliked wordnets; is that right?

yes. I think we have agreed to have links from OWN-PT to OWN-EN right? 

> in this case all the relations that are in own-en should also be in own-pt, and then the lack of the similarTo relations is a bug. if that's the case I'll open an issue.

Indeed, it seems we have a bug in the transformation of PT data. See http://wn.mybluemix.net/synset?id=01598592-a, in the OWN-EN we have a `sim` link

```
w: abnormal[1] ant normal drf noun.cognition:abnormality[1]
d: departing from the normal in e.g. intelligence and development
e: an abnormal personality
e: they were heartbroken when they learned their child was abnormal
mt: noun.cognition:psychological_science
sim: exceptional[2]
```

But this link is not presented in the web interface above. A bug in the ES loading @hmuniz? This is not a problem in the OWN-PT RDF because relations between synsets are not materialized in the OWN-PT graph. But the relation is on the PWN 3.0 graph, so the bug seems to be in the creation of the OWN-PT text files of this repository. right? 

See http://wnpt.sl.res.ibm.com:10035/#/repositories/wn30/node/%3Chttps://w3id.org/own-pt/wn30-en/instances/synset-01598592-a%3E

**Comment by arademaker** [comment]
Should I accept this PR and we take care of #2 later or should we fix this issue in this PR.

**Comment by odanoburu** [comment]
> Should I accept this PR and we take care of #2 later or should we fix this issue in this PR.

I'd say yes, accept this PR for now

thanks for opening the issue!

**Pull request merged**
